version: '3.8'

services:
  website:
    build:
      context: .
    container_name: website
    restart: always
    ports:
      - "8080:8080"  # Adjust port mapping if needed
    environment:
      MONGO_URL: 
