export enum ActionTypes {
    // AUTH
    Login = 'Login',
    LoginSuccess = 'LOGIN_SUCCESS',
    LoginFailed = 'LOGIN_FAILED',
    SIGN_OUT = 'SIGN_OUT',
    GET_USERS = 'GET_USERS',
    
    // POLYGONS
    GET_POLYGON_NAMES = 'GET_POLYGON_NAMES',
    GET_POLYGON_DETAILS = 'GET_POLYGON_DETAILS',
    GET_POLYGON_NAMES_REQUEST = 'GET_POLYGON_NAMES_REQUEST',
    GET_POLYGON_NAMES_SUCCESS = 'GET_POLYGON_NAMES_SUCCESS',
    GET_POLYGON_NAMES_FAILURE = 'GET_POLYGON_NAMES_FAILURE',
    GET_POLYGON_DETAILS_REQUEST = 'GET_POLYGON_DETAILS_REQUEST',
    GET_POLYGON_DETAILS_SUCCESS = 'GET_POLYGON_DETAILS_SUCCESS',
    GET_POLYGON_DETAILS_FAILURE = 'GET_POLYGON_DETAILS_FAILURE',
}